### ISSUE TITLE
[BUG] - Can't create a space in Safe app in Polygon PoS

### ISSUE THREAD

**Issue by utgarda** [snapshot-labs/snapshot#4465]
### Briefly describe the bug.

Oops, signature validation failed

### How can we reproduce the bug?

1. Go to https://app.safe.global/apps/open?safe=matic:0xDC28ae5C0c406FD78ec3e1eD62489f0fb0F7f03e&appUrl=https%3A%2F%2Fsnapshot.org use "+" button, the one annotated 'create space'
2. Click on 'next' on every page, filling details
3. Scroll down to 'create' button on the last page, and, after getting enough signatures
4. See error "Oops, signature validation failed"

### What is the expected behaviour?

On-chain transaction generation to set a Snapshot space for a Safe account

### Can you attach screenshots?

![image](https://github.com/snapshot-labs/snapshot/assets/15115/d1033acc-5797-409a-ab1d-f6af763913d3)

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - Manjaro Linux
3. OS Version - 6.6.7-4-MANJARO (64-bit)
4. Browser - Chrome
5. Browser Version - 118.0.5993.88 (Official Build) (64-bit)
6. Wallet - Rabbi, tried Metamask too
7. Space - tried creating a new one
8. Any additional information we should know - found Snapshot app while looking for DAO tooling in Safe apps, tried using it, everything works up to the moment when enough signatures are collected. No error logs appear at all when the red notification is shown, error logs below appear on re-visiting the last step of "Create a space" page after clicking "back" and "next" at the bottom.

```
Message PROPOSE event received Object
instrument.js:122 Message UPDATED event received Object
instrument.js:122 Message SIGNATURE_PREPARED event received Object
instrument.js:122 Message PROPOSE event received {messageHash: '0x83b3b52d93e026deb61c1d6c75e77b5930d63f2ab99c612a84fe3b6aa4977da7'}
instrument.js:122 Message UPDATED event received {messageHash: '0x83b3b52d93e026deb61c1d6c75e77b5930d63f2ab99c612a84fe3b6aa4977da7'}
instrument.js:122 Message SIGNATURE_PREPARED event received {messageHash: '0x83b3b52d93e026deb61c1d6c75e77b5930d63f2ab99c612a84fe3b6aa4977da7', requestId: 'b0ba91e340', signature: '0xa5dd9b209d1428880bae2d305e2a5c604c4870a82315835a…ae32988312c0298337fde1ea558348870bbf6941ccb3a431c'}
instrument.js:122 Message PROPOSE event received {messageHash: '0xea5842ad7cbf7e690d62af1479a8c41675e88f1fdb2251703aaf975995d2dc4a'}
instrument.js:122 Message UPDATED event received {messageHash: '0xea5842ad7cbf7e690d62af1479a8c41675e88f1fdb2251703aaf975995d2dc4a'}
instrument.js:122 Message SIGNATURE_PREPARED event received {messageHash: '0xea5842ad7cbf7e690d62af1479a8c41675e88f1fdb2251703aaf975995d2dc4a', requestId: 'd1db1d1965', signature: '0x4b67a54e46d9ff49594d87b668f3ab8824076228b75d927f…c7fcd2ce5aa88d24de013b75a6097444d663b5d5e67a62c1c'}
instrument.js:122 Message PROPOSE event received {messageHash: '0x0267eab56c85daabd7e81d27fe78628bb5cf7f87d080c663570c5ecf532c6768'}
instrument.js:122 Message UPDATED event received {messageHash: '0x0267eab56c85daabd7e81d27fe78628bb5cf7f87d080c663570c5ecf532c6768'}
instrument.js:122 Message SIGNATURE_PREPARED event received {messageHash: '0x0267eab56c85daabd7e81d27fe78628bb5cf7f87d080c663570c5ecf532c6768', requestId: '82f02b02f0', signature: '0x1702271e4630be2c6f22bba8ae6f4c140847767739cc6aa2…097247232d95b32899be7adfde5a9dac01ac99d3d0b3db31b'}
instrument.js:122 Message PROPOSE event received {messageHash: '0x542fdb7734c84f04488395e9e841e9230e050e44fb38303a4e5c070c663eb3c9'}
instrument.js:122 Message UPDATED event received {messageHash: '0x542fdb7734c84f04488395e9e841e9230e050e44fb38303a4e5c070c663eb3c9'}
instrument.js:122 Message SIGNATURE_PREPARED event received {messageHash: '0x542fdb7734c84f04488395e9e841e9230e050e44fb38303a4e5c070c663eb3c9', requestId: '15048af356', signature: '0x25f859813fe1d66fe24f20dafffe12da7e5e19b3d844a42d…f625ccff3c727a9998ed58ebb11b5eb07f1e62b999919011c'}
 TypeError: Cannot read properties of undefined (reading 'plugins')
    at s1.fn (snapshot.org/assets/…e046fa.js:841:46104)
    at s1.run (snapshot.org/assets/…51e046fa.js:6:31463)
    at get value [as value] (snapshot.org/assets/…51e046fa.js:6:40665)
    at _ (snapshot.org/assets/…51e046fa.js:6:39216)
    at snapshot.org/assets/…e046fa.js:841:46767
    at r (snapshot.org/assets/…51e046fa.js:6:44243)
    at Tt (snapshot.org/assets/…51e046fa.js:6:61090)
    at snapshot.org/assets/…e046fa.js:129:63517
    at Object.r [as default] (snapshot.org/assets/…51e046fa.js:6:44243)
    at Proxy.<anonymous> (snapshot.org/assets/…51e046fa.js:6:53583)
    at Vb (snapshot.org/assets/…51e046fa.js:6:44555)
    at s1.Ze [as fn] (snapshot.org/assets/…51e046fa.js:6:81803)
    at s1.run (snapshot.org/assets/…51e046fa.js:6:31463)
    at ue.update (snapshot.org/assets/…51e046fa.js:6:82105)
    at $ (snapshot.org/assets/…51e046fa.js:6:82134)
    at y (snapshot.org/assets/…51e046fa.js:6:80851)
G0e @ snapshot.org/assets/index.51e046fa.js:6
ap @ snapshot.org/assets/index.51e046fa.js:6
Vb @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
$ @ snapshot.org/assets/index.51e046fa.js:6
y @ snapshot.org/assets/index.51e046fa.js:6
B @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
$ @ snapshot.org/assets/index.51e046fa.js:6
y @ snapshot.org/assets/index.51e046fa.js:6
B @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
M @ snapshot.org/assets/index.51e046fa.js:6
S @ snapshot.org/assets/index.51e046fa.js:6
F @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
$ @ snapshot.org/assets/index.51e046fa.js:6
y @ snapshot.org/assets/index.51e046fa.js:6
B @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
$ @ snapshot.org/assets/index.51e046fa.js:6
y @ snapshot.org/assets/index.51e046fa.js:6
B @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
M @ snapshot.org/assets/index.51e046fa.js:6
S @ snapshot.org/assets/index.51e046fa.js:6
F @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
M @ snapshot.org/assets/index.51e046fa.js:6
X @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
$ @ snapshot.org/assets/index.51e046fa.js:6
y @ snapshot.org/assets/index.51e046fa.js:6
B @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
W @ snapshot.org/assets/index.51e046fa.js:6
X @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
W @ snapshot.org/assets/index.51e046fa.js:6
X @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
W @ snapshot.org/assets/index.51e046fa.js:6
R @ snapshot.org/assets/index.51e046fa.js:6
F @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
W @ snapshot.org/assets/index.51e046fa.js:6
X @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
W @ snapshot.org/assets/index.51e046fa.js:6
R @ snapshot.org/assets/index.51e046fa.js:6
F @ snapshot.org/assets/index.51e046fa.js:6
g @ snapshot.org/assets/index.51e046fa.js:6
Ze @ snapshot.org/assets/index.51e046fa.js:6
run @ snapshot.org/assets/index.51e046fa.js:6
ue.update @ snapshot.org/assets/index.51e046fa.js:6
Su @ snapshot.org/assets/index.51e046fa.js:6
rj @ snapshot.org/assets/index.51e046fa.js:6
Promise.then (async)
nj @ snapshot.org/assets/index.51e046fa.js:6
oy @ snapshot.org/assets/index.51e046fa.js:6
(anonymous) @ snapshot.org/assets/index.51e046fa.js:6
bB @ snapshot.org/assets/index.51e046fa.js:6
ew @ snapshot.org/assets/index.51e046fa.js:6
ry @ snapshot.org/assets/index.51e046fa.js:6
(anonymous) @ snapshot.org/assets/index.51e046fa.js:6
bB @ snapshot.org/assets/index.51e046fa.js:6
ew @ snapshot.org/assets/index.51e046fa.js:6
ry @ snapshot.org/assets/index.51e046fa.js:6
(anonymous) @ snapshot.org/assets/index.51e046fa.js:6
bB @ snapshot.org/assets/index.51e046fa.js:6
ew @ snapshot.org/assets/index.51e046fa.js:6
ry @ snapshot.org/assets/index.51e046fa.js:6
(anonymous) @ snapshot.org/assets/index.51e046fa.js:6
bB @ snapshot.org/assets/index.51e046fa.js:6
ew @ snapshot.org/assets/index.51e046fa.js:6
ry @ snapshot.org/assets/index.51e046fa.js:6
(anonymous) @ snapshot.org/assets/index.51e046fa.js:6
bB @ snapshot.org/assets/index.51e046fa.js:6
ew @ snapshot.org/assets/index.51e046fa.js:6
ry @ snapshot.org/assets/index.51e046fa.js:6
set value @ snapshot.org/assets/index.51e046fa.js:6
X @ snapshot.org/assets/…dex.51e046fa.js:123
(anonymous) @ snapshot.org/assets/…dex.51e046fa.js:123
Promise.then (async)
I @ snapshot.org/assets/…dex.51e046fa.js:123
A @ snapshot.org/assets/…dex.51e046fa.js:123
m @ snapshot.org/assets/…ex.51e046fa.js:1172
Su @ snapshot.org/assets/index.51e046fa.js:6
xs @ snapshot.org/assets/index.51e046fa.js:6
J0e @ snapshot.org/assets/index.51e046fa.js:6
re.onNext.a.<computed>.a.<computed> @ snapshot.org/assets/…ex.51e046fa.js:1161
Su @ snapshot.org/assets/index.51e046fa.js:6
xs @ snapshot.org/assets/index.51e046fa.js:6
J0e @ snapshot.org/assets/index.51e046fa.js:6
p @ snapshot.org/assets/…ex.51e046fa.js:1160
Su @ snapshot.org/assets/index.51e046fa.js:6
xs @ snapshot.org/assets/index.51e046fa.js:6
n @ snapshot.org/assets/index.51e046fa.js:6
```

**Comment by ChaituVR** [comment]
Only mainnet Safes can create/edit spaces
